### ISSUE TITLE
Add dependencies pls

### ISSUE THREAD

**Issue by saritasa** [jam-py/jam-py#1]
Hi Andrew,

pls add depdendencies so you can run them with pip -r

thanks,
Dmitry

**Comment by saritasa** [comment]
when I run I get this:
ImportError: No module named gobject

**Comment by jam-py** [comment]
Can you exlpain the problem more so I can repeat it.

**Comment by jpscaletti** [comment]
``pip`` can install dependencies automatically from a list in a text file. It is customary in the Python world  to name that file ``requirements.txt``:

    pip install -r requirements.txt

Because you didn't have it, saritasa probably believed that your project didn't need any.

For non-python dependencies like GTK you should name them in the README

**Comment by jam-py** [comment]
I am sorry, but jam.py installation package do not use any third party packages except web.py. So there is no need for the dependencies list. I have just installed it several times and everything works well. May be Dmitry tried to install it in Python 3. Jam.py do not support Python 3. Any way I'm very gratefully to Juan-Pablo for help.
Andrew Yushev
