### ISSUE TITLE
How to show related Item (not Detail) in a subform?

### ISSUE THREAD

**Issue by tagwato** [jam-py/jam-py#107]
Hi, testing Jam.py for a couple of hours.
Great work you have done so far, congratulations!

I see that Jam.py has a Detail feature, which allows synchronized navigation in a "master-detail" fashion. So, if an Entity (Item) has an associated Detail, we can enable this feature via "View form" and "Edit form" button of the application builder.

But, this only works if we have previously  designed the Detail form, via "Detail" button.

However, sometimes we need this kind of synchronized navigation to be used with two entities (Item), instead of an Item and a Detail.

For instance, in the Documentation tutorial we create two Items: Customer and Contacts. 
The question is: How can I show a Customer form and below it a related Contacts form (acting as a subform, so that it shows only the records whose customer is the customer shown in the selected record of the Customer form above it)?

So what we want is to show Catalog (Item) form as if it were a Detail form of the Customer (Item) form. 

Creating a Detail, in this case, would be just a waste of time, because we would have to look up every field of the detail in the original Catalog Item.

So, It seems that it would be a nice thing if we could assign this kind of relationship between Items and show it master-detail forms without the need to create a Detail.

By the way, this is a cool thing that we do in MS Access, with a few clicks and selections. 
I'm sure Jam.py can be that easy, too!

**Comment by platipusica** [comment]
Hi,

Not sure I follow. I think you need to create a Detail, since Jam cant do
that automatically for now.

The sub details can be created as many as needed.
My wip project is here:

https://jampy.pythonanywhere.com/

Look for Assignments.

D.

**Comment by jam-py** [comment]
Hi,
There is a topic in the docs that explains how to link two tables:
http://jam-py.com/docs/how_to/how_to_link_two_tables.html
Regards,
Andrew yushev

вс, 4 авг. 2019 г. в 04:39, platipusica <notifications@github.com>:

> Hi,
>
> Not sure I follow. I think you need to create a Detail, since Jam cant do
> that automatically for now.
>
> The sub details can be created as many as needed.
> My wip project is here:
>
> https://jampy.pythonanywhere.com/
>
> Look for Assignments.
>
> D.
>

**Comment by tagwato** [comment]
> 
> Hi, There is a topic in the docs that explains how to link two tables: http://jam-py.com/docs/how_to/how_to_link_two_tables.html Regards, Andrew yushev вс, 4 авг. 2019 г. в 04:39


Thanks Andrew.
In fact, that example still uses a Detail in the detail subform, from which we can navigate to the Item (in that case, the Invoice). 
Nevertheless, following the example I was able to create a master-detail navigation using two Items, without the need to define a Detail !

My project uses the Customers and Contacts entities (Items) of the Documentation tutorial.
There I create a synchronized navigation from Customers to Contacts (both are Items, no Detail was defined).

Here are the javascript code that works:

```
function on_view_form_created(item) { 

    if (!item.lookup_field) {
        item.table_options.height -= 200;
        item.contacts_table = task.contacts.copy(); //creates a dynamic contacts_table, cloned from Contacts 
        
        item.contacts_table.paginate = false;  //no navigation buttons

        item.contacts_table.create_table(item.view_form.find('.view-detail'), { //every form has a "view-detail" section
            height: 200 ,
            summary_fields: ['phone'] //,
            //on_dblclick: function() {
            //    show_contact(item.contact_table);  //not needed, the default double click works well
            //}
        });
        refresh_contacts(item);
        item.alert('Double-click a record in the bottom table to see/edit a contact of the customer.');
    }
    add_show_contacts_button(item); //testing alternative approach
} 
```

```

var scroll_timeout;


function on_after_scroll(item) { //here we have item=customers object
    if (!item.lookup_field && item.view_form.length) {
        clearTimeout(scroll_timeout);
        scroll_timeout = setTimeout(refresh_contacts(item), 100);
    }
}
```

```

function refresh_contacts(item) { //here we have item=customers object
    if (item.rec_count) {
        item.contacts_table.set_where({customer__eq: item.id.value});
        item.contacts_table.set_order_by(['-contact_date']);
        item.contacts_table.open(true);
    }
    else {
        item.contacts_table.close();
    }
}

```

So, the answer to my original question is: Yes, it is possible to show a related Item in a subform, without the need to create a Detail in the application builder.

By the way, I also tested an alternative approach, which relies on a button dynamically inserted in the Customers form (javascript code below):


```
//ALTERNATIVE APPROACH - Shows a Contacts dialog filtered by the selected Customer
// See: http://jam-py.com/docs/refs/client/item/m_open.html
function add_show_contacts_button (item) {
    var btn = item.add_view_button('Contacts of selected customer'); 
    btn.click( function() { 
        var customer_id = task.customers.id.value;  //get id of current selected customer
        item.alert('selected customer is: ' + customer_id);
        var filteredContacts = task.contacts.copy();

        filteredContacts.set_where({customer__eq: customer_id});// BUG? this where clause  is not working !!!
        filteredContacts.set_order_by(['-contact_date']);
        filteredContacts.open();        
        
//        Also didn't work:
//        filteredContacts.open({
//            where: {'customer__eq': customer_id},  // BUG? this where clause  is not working !!!
//            order_by: ['contact_date']
//        }); 

//        filteredContacts.view();  //it works, but the WHERE clause we previously set is not applied in the view
        filteredContacts.create_view_form();  //it works, but the WHERE clause we previously set is not applied in the view
    });     
}
```

However, there is a problem with the alternative approach: it seems that the filter we set with the WHERE clause is not being applied.

Any clue why this is happening?

PS - Trying to append the project ZIP file, but can't find an option in this comment page to do that.

**Comment by platipusica** [comment]
Just drop the file into the comment...

Thx

**Comment by rrad0812** [comment]
Hi,
I think we have a communication problem.

If the two entities (tables, items) are in a relationship, then each other must be parent (1: n) or child (n: 1) or both (m: n). The 1: 1 case is a special case of these above. MS Access or other tools ( including Jam.py ) cannot create a form with tables unless one of the above relational links is established.

When a relational connection is established, we have a child-side foreign key defined. In the case of Jam.py it is master_record_id and it can be aliased (renamed). An item that has a foreign key defined in this way in Jam.py jargon is a Detail item.

What Andrew tried to tell you was that you could do it from scratch. His howto example is one sub-case, which can otherwise be obtained directly from the appbuilder, but with the repositioning of the requested record in item detail.  

On the other hand, you are trying to do the same by filtering out details item, which each tool does automatically, if you create a story with relationships.

PS. And I think this was for the group. Here, however, there should be questions regarding concrete implementation.

Cheers,
Radosav

**Comment by tagwato** [comment]
> Hi,
> I think we have a communication problem.
> 
> If the two entities (tables, items) are in a relationship, then each other must be parent (1: n) or child (n: 1) or both (m: n). The 1: 1 case is a special case of these above. MS Access or other tools ( including Jam.py ) cannot create a form with tables unless one of the above relational links is established.
>....
>.... 
> Cheers,
> Radosav

Hi, Radosav.
Thanks for your explanation.


Regarding this statement, I believe there is some misunderstanding: "MS Access or other tools ( including Jam.py ) cannot create a form with tables unless one of the above relational links is established."

In fact, in MS Access one CAN create forms without establishing relational links between the entities (tables).  The sample project attached shows that it is possible (see the form "frmCustomers-with-Contacts").

[_Customers-and-Contacts-in-master-detail-form-without-referential-integrity.zip](https://github.com/jam-py/jam-py/files/3469917/_Customers-and-Contacts-in-master-detail-form-without-referential-integrity.zip)


You are right that this kind of situation is (probably) bad design, and we should always establish the relational links.

Anyway, if that happens in a project for whatever reason, my question was: how to deal with these situations in Jam.py, if a master-detail form is needed with 2 entities (no Detail)? Well, we already saw the answer in previous posts.

**Comment by platipusica** [comment]
You can, 

but with no Detail you are missing a lot of functionality. Like History, Deleted, etc...It takes only a couple of minutes to create a Detail.
What Jam is trying to do is to enable Details with not to much programming for the User ;)

BR

**Comment by tagwato** [comment]
> You can,
> 
> but with no Detail you are missing a lot of functionality. Like History, Deleted, etc...It takes only a couple of minutes to create a Detail.
> What Jam is trying to do is to enable Details with not to much programming for the User ;)
> 
> BR

Ok. If I understood correctly, from your explanation (and Andrew's and Radosav's), a Detail is the right way to model the N side of a relationship in Jam.py.
Doing so, the framework assures relational integrity and makes our work easier, including form's design.
As a feedback, I'd like to point that the tutorial in the Documentation does NOT follow this pattern (shouldn't Contacts entity  be a Detail?).
I know the tutorial is an incomplete example, but it gave me the impression that the relationship between Customers x Contacts was modelled in accordance with the framework's patterns (and then... I saw the need for a master-detail form showing Customers x Contacts).
I think the tutorial was the main reason I opened this question (issue).

**Comment by rrad0812** [comment]
As I said before, we have a communication problem.

Just because you didn't create a relationship in ms access or anything other but put a 'Customer' key in the 'Contacts' child table and create a filter doesn't change the essence. The only thing you have to do is maintain it yourself, and it's not quite that simple, is it? After all, this is just what the framework needs.

>> how to deal with these situations in Jam.py, if a master detail is needed with 2 entities (no Detail)?

Andrew replied. In the Demo application, you have a track item and an Invoices detail item is raised from scratch. Here he showed how to connect from scratch in a framework two items, **neither of which is detail to the other.** Yes, it is not enough for an item to be a detail, it needs to be a detail for the choosing item in the Journals or Catalogs group. Only then do the framework's capabilities.

Therefore, the right answer for you is, in order to have two related items, you need to have a foreign key in one of them, and then you can either 
- declare the item with foreign key as a detail, and in the master item define  the same as the detail item or 
- as Andrew did in the demo application, do the same thing out of hand.  ( Just like you did in ms access. )

**Comment by jam-py** [comment]
I think that the topic of details is poorly described in the documents, as, @tagwato  quite rightly, writes
Especially the difference between the detail linked to the master and an item whose owner is a detail group. There is a lot of confusion concerning it. I plan to write a topic explaining this in more detail.

May be it is due to the fact that both of them are called "detail" and there is a need to name
the items that detail group owns differently. But I can not come up with a name.
If you have some ideas please write.

Regards,
Andrew Yushev
