### ISSUE TITLE
Thousand separator

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#122]
Hi,

Is thousand separator applied for Currency field only? I have Integer and Float data type, but none of them get thousand separator.

**Comment by jam-py** [comment]
Hi,
Thousand separator is for Currency field only now.
I'll think about adding for numeric types.

вс, 25 авг. 2019 г. в 18:47, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Thank you, I look forward to seeing that.

**Comment by jam-py** [comment]
You know, I have not decided yet whether I will add this feature and
in any case, it will not be soon.
If you need this separator you can write on_field_get_text event handler
for this fields.



пн, 26 авг. 2019 г. в 18:06, PaulSanZa <notifications@github.com>:

**Comment by rrad0812** [comment]
Hi, you two
I already had such a problem in Jam.py
The problem is related to Regional settings, ie locale settings, and has different behavior on Pyton 2.7 or Python 3.7 versions.

On systems that have the surrogate settings of the above settings, for example, my default OS is cp 1252, while changing additional settings to cp 1250, python does not see additional settings, ie locale_default is at cp 1252.

Then there is the problem of parcialy escaping a comma. 

The only patch I could use was to set the appropriate locale_default at the start of the code. It's not that simple, it has a few parameters, one of which is further propagated.

Or the simpler version is to convert values to a string and force a comma change.

Regards,

**Comment by PaulSanZa** [comment]
Hi @jam-py ,

I was out of town for a while and didn't check your reply. I'm not in hurry to use the feature, just asked whether it's intentionally applied to currency fields.
