### ISSUE TITLE
Password hashing

### ISSUE THREAD

**Issue by MatFluor** [jam-py/jam-py#123]
I think it would be great to adjust user management a bit to the safer side:
Here a few pointers maybe (please tell if I missed something in the backend that would negate this stuff):
- Admin shouldn't be able to see passwords
- Admin should only be able to reset/set new password for a user
- User should be able to change his password or have a way to reset it
(- Registration: Usually I don't do stuff where random users would register themselves, but it would be a nice option to have if it's needed)

My main thing is that the passwords are visible by default. App Mode is Production & Safe.

I know about the Authentication project (ImportError though with SQLite, others not tested) - but I think that this should merge into the "main functionality", with opt-out, rather than a lot of coding to achieve it.

**Comment by platipusica** [comment]
Hi Matthias,

Jam.py can work flawlessly with AD or LDAP(s), hence, the passwords
are a bit outdated in corporate world. Or even Universities.

Every single service out there now supports OAuth or some SSO. Not to
mention MFA's at.al. So in reality, the passwords are just one
mechanism of many.

Which one will dominate is a good question and will be interesting to
see in the future.

Registration is there. And the password reset :)

Here is the registration form. Have a look at the Jam version 5.4.52
how was implemented.

Hope this helps.


D.

**Comment by platipusica** [comment]
Here is the code for registration and the reg form. 

Add in Task/Server Module:

def on_ext_request(task, request, params):
    reqs = request.split('/')
    if reqs[2] == 'register':
        name, login, password = params
        users = task.app.admin.sys_users.copy(handlers=False)
        users.set_where(f_login=login)
        users.open()
        if users.record_count():
            return 'Existing username, please use different username'
        users.append()
        users.f_name.value = name
        users.f_login.value = login
        users.f_password.value = password
        users.f_role.value = 2
        users.post()
        users.apply()



[regist.html.zip](https://github.com/jam-py/jam-py/files/3543913/regist.html.zip)

**Comment by rrad0812** [comment]
Hi,
I think @MatFlour has a very right view of the matter.

1. Initially visible password,
2 The user must change the password when logging in for the first time
3. Furthermore, the user can change the password as needed
4. User registration in this type of software is not required
5. Everything should be part of the basic package, without additional coding

The initial setup of the framework with users and rolls within the definition sqlite project file was probably suboptimal. It should probably be split so that the rolls remain in the project file, while users should be part of the user database.

This is the first of my great wishes for Jam.py

And second, the other would be the possibility of a real add-on, then you probably wouldn't even talk about all this.

Unfortunately @platipusica is right, on planet Earth the day only takes 24 hours.

Regards,

**Comment by jam-py** [comment]
Please see http://jam-py.com/docs/how_to/authentication/index.html
