### ISSUE TITLE
batch data upload

### ISSUE THREAD

**Issue by mg64ve** [jam-py/jam-py#128]
Hello, I have tried to upload data to mySQL database but jam.py does not see that data.
Data contains fields and files.
Could you please give me some guidance on how to import data in a jam.py database from other sources?
Thanks.

**Comment by platipusica** [comment]
Hi,
Did you import the project first? If u did, you should be able to import data from sqlite, if sqlite3 was initially used.

If did not import project, than u need to import the tables from mysql. Than u will see them. Of course, that will not recreate the project. But, u can still import it over existing tables.

BR

**Comment by mgazzin** [comment]
thanks for your reply @platipusica 
I am not sure if I was clear.
Suppose I have the following catalog:

catalog name: images
fields:

name: TEXT
myimage: IMAGE

then on disk I have a csv file containing:

george, george1.png
karl, karl101.png
katia, katia02.png

and in same folder I have .png files.
My jam.py projects has MySQL database and it is already defined manually.
At this stage, how can I import data I have on disk into the database in the way jam.py can see that data? Specially for IMAGE or FILE data.

Do you get my point?

**Comment by platipusica** [comment]
Ok,

Not sure that u are placing images at the correct place.
Look at the Demo where the images are.

On grand scale that was done here:

https://jampy.pythonanywhere.com/

Hope this helps.

**Comment by mg64ve** [comment]
Thanks @platipusica 
Do you have any example in python?

**Comment by platipusica** [comment]
Not sure what you mean "in python"?
The above jam.py app has 500 000 images :) It's actually one singe image used for everything, but anyway.
Your images must be in static/files folder I think.

So if your file is 1.svg, this is what I did:

update SIMPLEASSETS_parts set PHOTO = '1.svg';
Which makes:
sqlite> select * from  SIMPLEASSETS_parts;
164377|0||n/a|1|BKUGvpdUm|1|0.99|2||12.0|46|1.svg
164378|0||n/a|1|KhalMkiypc|1|0.99|54||12.0|65|1.svg
.
.
You must have 1.svg in above folder and it jam.py will show it. Jam does NOT import images or files. 

It's really simple so not sure where the problem is....

**Comment by mg64ve** [comment]
ah ok @platipusica 
jam.py does not use BLOB.
I see now it store images and files in ./static/files.
So the only thing I need to do is to move the file in ./static/files and then update database.

Thanks.
You can close this ticket.
Cheers

**Comment by platipusica** [comment]
Glad to help.

Regards
