### ISSUE TITLE
DB Field named "label" will break the intended styling of a view lookup.

### ISSUE THREAD

**Issue by jim-fuller** [jam-py/jam-py#134]
![image](https://user-images.githubusercontent.com/12518763/72472411-1e449300-37aa-11ea-9c86-2b2e56159028.png)

[From Image]

1. Any DB Field named "Label" or "label" will cause styling issues in a view lookup as show in the pic.
2. Renaming the field where DBField <> "label" or DBField <> "Label" solves the problem.

**Comment by jam-py** [comment]
Jim, I see the problem.

It is because the app adds class with name of the field to
html tags so developer can access it if needed
and there is a class with name label.
The same is with badge.
I'll think how to solve it.

Thank you for the information!


чт, 16 янв. 2020 г. в 00:20, jim-fuller <notifications@github.com>:

**Comment by jim-fuller** [comment]
Sure thing !
