### ISSUE TITLE
Same missing label on form

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#145]
I've installed Jam-py 5.4.90 I see same label are not in traslation list, so I can't traslate it.
Here some of it:
![immagine](https://user-images.githubusercontent.com/11799153/74598680-06488380-5076-11ea-83dd-18e1effd21e4.png)
(history_button, Detail height, Buttons on top)

and

![immagine](https://user-images.githubusercontent.com/11799153/74598690-3b54d600-5076-11ea-8adb-ffba5dd07276.png)

(history_button, Detail height, Buttons on top)

![immagine](https://user-images.githubusercontent.com/11799153/74598732-08f7a880-5077-11ea-8212-74911df54ca1.png)

(Lookup Lists)

![immagine](https://user-images.githubusercontent.com/11799153/74599337-63493700-5080-11ea-843b-0a641ca564df.png)

(Striped)

Can you add them?

Thanks.
Fabio

**Comment by platipusica** [comment]
Hi Fabio,

good point! Thanks for reporting.

Since Jam has Export/Import for Langs I would expect that ANY string added into the Exported file, and Imported after, would be instantly used.

Just tried with history_button, Imported and nothing happened:

```
select * from JAM_LANG_KEYS where F_KEYWORD like 'history%';
289|history
```
But than:

```
insert into JAM_LANG_KEYS (f_keyword) values ('history_button')
insert into JAM_LANG_VALUES (f_lang,f_key,f_value) values (1, 317, 'History Button');
select * from JAM_LANG_KEYS where F_KEYWORD like 'history%';
289|history
317|history_button
```

Restarted App and it's there.

Jam should not really rely on modifying Export file at all.

Andrew?


[English_en-US_2020-02-17_11-50-25.lang.zip](https://github.com/jam-py/jam-py/files/4211781/English_en-US_2020-02-17_11-50-25.lang.zip)

**Comment by jam-py** [comment]
Thank you!
I'll add them

пн, 17 февр. 2020 г. в 07:46, platipusica <notifications@github.com>:

**Comment by jam-py** [comment]
@platipusica, you are write, but it would be better if I add them myself.

**Comment by platipusica** [comment]
Sorry, I've deleted the above comment by mistake. It was for me anyway..

**Comment by jam-py** [comment]
Thank you for the video!

The problem with internalization is that it needs time.
I know how to do it a long ago.
Anyway thank you.



пн, 17 февр. 2020 г. в 11:46, platipusica <notifications@github.com>:
