### ISSUE TITLE
Linked table mixed with tabbed details

### ISSUE THREAD

**Issue by xelomac** [jam-py/jam-py#164]
Hi everybody,

I linked an item table successfully following the documentation:
https://jam-py.com/docs/how_to/how_to_link_two_tables.html
The table appears in the div.view-detail as expected. But as soon as I add a detail through the GUI to the same item the linked table disappears. 

So my question is the following: How can I add one or more linked tables to one or more details of an item so that they appear as tabbed content at the detail position? And how can I control the the order of the tabs?

I am grateful for any hint...

**Comment by platipusica** [comment]
Hi,
have a look in here:
https://jampy.pythonanywhere.com/builder.html

Journals/View Form/Form - 2 details selected. This is how you the link tables. As many needed.

And than click on "Assets with Parts" in Journals, Up/Down controls the Tab position.

Export project and play...

To link tables, no need for any code. The above Doc describes additional actions for this specific scenario, like "Double-click the record in the bottom table to see the invoice in which the track was sold.", etc...

Cheers
D.

**Comment by platipusica** [comment]
Like this Librarian demo, only code needed is to update readers_log since we can do that in bulk - with as many books as selected on "Select books" .

Hope this helps.
[lib_1.0.1_5.4.96_2020-06-23_14-12-02.zip](https://github.com/jam-py/jam-py/files/4817429/lib_1.0.1_5.4.96_2020-06-23_14-12-02.zip)

**Comment by jam-py** [comment]
Hello,

The linked table disappears because it uses the same container div
with view-detail class as
the GUI detail. You can add another div to the view form template which
will be the container
for linked table <div class="view-link"></div>
https://jam-py.com/docs/programming/interface/form_templates.html

Below is a template for invoices view form from demo app with this div:

            <div class="invoices-view">
                <div class="form-body">
                    <div class="view-table"></div>
                    <div class="view-link"></div>
                    <div class="view-detail"></div>
                </div>
                <div class="form-footer">
                    <button id="delete-btn" class="btn expanded-btn
pull-left" type="button">
                        <i class="icon-trash"></i> Delete<small
class="muted">&nbsp;[Ctrl+Del]</small>
                    </button>
                    <div id="report-btn" class="btn-group dropup">
                        <a class="btn expanded-btn dropdown-toggle"
data-toggle="dropdown" href="#">
                            <i class="icon-print"></i> Reports
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu bottom-up">
                        </ul>
                    </div>
                    <button id="edit-btn" class="btn expanded-btn"
type="button">
                        <i class="icon-edit"></i> Edit
                    </button>
                    <button id="new-btn" class="btn expanded-btn"
type="button">
                        <i class="icon-plus"></i> New<small
class="muted">&nbsp;[Ctrl+Ins]</small>
                    </button>
                </div>
            </div>

If you need these details in tabs you can use the add_tab method.
https://jam-py.com/docs/refs/client/task/m_add_tab.html
<https://jam-py.com/docs/refs/client/task/m_add_tab.html?highlight=tabs>
and you should not use GUI for the detail and write the code for opening
detail
in the on_after_scroll event handler

Regards,
Andrew Yushev



вт, 23 июн. 2020 г. в 09:13, platipusica <notifications@github.com>:

**Comment by xelomac** [comment]
Thank you very much. It works so far. I can now display standard details created with the GUI side by side with custom details in tabs using the add_tab method for both of them. I also managed to display the same tabbed details in a modal dialog when editing the master record by writing an on_edit_form_created function. By double clicking the detail records I can even edit the detail records in an automatically opened modal form (standard behaviour). Now I am looking for an elegant way to add new-, edit-, and delete-buttons below my details view like normal GUI generated detail views are coming with. Is there something prepared behind the scenes that I can use or do I have to create my own buttons with on click event functions and so on?

**Comment by jam-py** [comment]
I am afraid there is no standard way to do it.

сб, 4 июл. 2020 г. в 18:23, xelomac <notifications@github.com>:
