### ISSUE TITLE
🚨 Potential Cross-site Scripting (XSS) - Stored (CWE-79)

### ISSUE THREAD

**Issue by huntr-helper** [jam-py/jam-py#207]
👋 Hello, @jam-py - a potential high severity Cross-site Scripting (XSS) - Stored (CWE-79) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-jam-py/jam-py** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

✏️ **NOTE**: If we don't hear from you in *14 days*, we will proactively source a fix for this vulnerability (and open a PR) to ensure community safety.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by Aravindha1234u** [comment]
Hey @jam-py, This PR was opened from huntr.dev which to fix #195, if you verify and comment here then I can commit for the fix.

**Comment by jam-py** [comment]
Hi, @Aravindha1234u, thank you!
I am working on it now.

**Comment by Aravindha1234u** [comment]
Yeah once you approve the submission I will be able to create PR for fix

**Comment by jam-py** [comment]
ok, thanks

**Comment by jam-py** [comment]
Hi, @Aravindha1234u 
I fixed the problem, the history fields are sanitized now

**Comment by JamieSlome** [comment]
@jam-py @Aravindha1234u - great work all! 🍰 

Going to reflect this in our database and award the bounty for the disclosure, cheers!

**Comment by jam-py** [comment]
Thanks!

вс, 9 мая 2021 г. в 17:41, Jamie Slome ***@***.***>:

**Comment by platipusica** [comment]
@Aravindha1234u @JamieSlome at.al

this issue:
https://huntr.dev/bounties/2-other-jam-py/jam-py/

is not correct. Infact, this statement:
"Clone from GitHub repo and build in local or visit demo page: https://jampy.pythonanywhere.com/
Click on the suppliers option and select any supplier and edit the comment field with payload
Try to edit and javascript code will be executed."

Is not true since it is read only application. There is no way to upload the payload. This is clearly visible on the screenshot:
"Errror
This is a demo version with limited functionality. You are not allowed to write changes to the database. The full-featured version is located in the demo folder of the Jam.py package"

Also, "Clone from GitHub repo" - which repo? The App lives here on github:
https://github.com/platipusica/simpleassets

None of my repos are writable, so the problem does not exist.

Please update your issue accordingly. 
Thanks.

**Comment by Aravindha1234u** [comment]
@platipusica No I i just gave demo page for testing, but its actually vulnerable package. You can tried in local. If you want I post a video here.

**Comment by platipusica** [comment]
@Aravindha1234u 
than it has nothing to do with https://jampy.pythonanywhere.com/ :)

We have been through this, referencing read only Application on the Net, and local sandbox is not the same. You'll find many of my read only Apps out there, are we making an issue when it does not exist?

**Comment by Aravindha1234u** [comment]
@platipusica its not about readonly, even then the javascript code will be executed which is reflected xss. And when we deploy it in local and try the same it becames stored xss.

I will just edit the disclosure so everything becomes clear.

**Comment by platipusica** [comment]
I am asking why is my site there as a reference? Since the package maintainer is asking me to update the site with a new package?
And you referenced github build which is NOT correct:
"Clone from GitHub repo and build in local or visit demo page: https://jampy.pythonanywhere.com/" 

If you build in local what this build has to do with jampy.pythonanywhere.com?

**Comment by platipusica** [comment]
In other words, @jam-py is working on the issue, there is no need to reference other sites out there since this is not maintainer problem.

Thanks
