### ISSUE TITLE
Renaming,deleting columns doesn't commit changes to database, v4.0.78

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#41]
Hi, 

I think this is a bug with sqlite3. Did not check the other DB's. 

Dean

**Comment by jam-py** [comment]
Hi, Dean
You are a very good tester!

I made it so that deleting the field in Administrator does not delete field from DB table for SQLITE in the latest version.

SQLITE does not have drop or change field command and before the table was renamed, a new table created and records were copied. It is not good for many reasons. This change as well allows importing of metadata.

I can do a button in Admin in DB manual mode to recreate a table to get rid of deleted fields. Do you think I should do it? 

Kind regards,
Andrew
