### ISSUE TITLE
Import types

### ISSUE THREAD

**Issue by kobzar** [jam-py/jam-py#49]
When we do import table from exist database rows type doesn't correct.
So we must change it for each string by hand.
When table is small - this is not the problem, but when table - large....

**Comment by dbabicwa** [comment]
Hi there

Is there an actual problem with the import or works ok? Which db you're importing since if importing from sqlite3 there is no need for that? For sure the Oracle datatypes is a huge topics and jam (or any other tool) can only suggest the datatype but really the decision is yours.
For example, Oracle Date is it a timestamptz or date in postgres? Or Number(x,y) is it bigint or int? You need to decide unfortunately. 

Cheers

D.

**Comment by jam-py** [comment]
Hi

Jam.py has a limited set of data types that are just wrappers over actual
DB types.
This way you could move from one DB to another without changing the project.
As Dean writes you have to select the appropriate type.
If you send me corresponding pairs: dbtype - jam.py type
I can try to automate the import.

Andrerw

2017-09-18 10:18 GMT+03:00 dbabicwa <notifications@github.com>:
