### ISSUE TITLE
History does not show the record id

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#98]
Hello,

Using the history feature i can see the old value and new value of the field being changed, but not actually the name of the field being changed.

It's very hard to understand precisely the change that happened.
Davide

**Comment by jam-py** [comment]
Hello, Davide

The algorithm used saves the field values before the change and, when the
changes are saved, writes the changed fields,
date of change and user id.

Regards,
Andrew Yushev


пн, 11 мар. 2019 г. в 15:55, Davide Bortolami <notifications@github.com>:

**Comment by platipusica** [comment]
I just tried, it is NOT showing old value for the FirstName.


![Screenshot from 2019-03-12 15-37-50](https://user-images.githubusercontent.com/9026100/54182584-e19a7200-44dc-11e9-8f4c-02118f6cd8e9.png)

**Comment by jam-py** [comment]
I changed jam.py so that the history does not save the old values to
minimize the disk space it occupies.
Andrew

вт, 12 мар. 2019 г. в 10:39, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Actually, only the old values are important, since the new ones are displayed already :)

**Comment by jam-py** [comment]
A history record shows who set the value and when he did it.
The old values are in previous records of the history.

**Comment by ddavidebor** [comment]
Hello,
Sorry i used the wrong terminology.

What I meant to say is: I cannot identify from the provided information which record was changed.

The information provided is:
* table
* old value
* new value

The information missing is:
* record (id? )

If you want to look around, the best table history i've seen is from the framework [directus](https://directus.io/).

**Comment by jam-py** [comment]
Davide, history of all items(tables) is stored in the history item (table)
that has the following fields:

item_id - unique ID of the item
item_rec_id - primary field value of the record that has been changed
operation - 1 - inserted, 2 - modfied, 3 - deleted
changes - list of field ID, field value pairs
user - user name
date - date of change

When you click on history button to see the history on the record the
record id is the id of the selected record

Regards,
Andrew


вт, 12 мар. 2019 г. в 14:37, Davide Bortolami <notifications@github.com>:

**Comment by platipusica** [comment]
If we look at the screenshot, the OLD value is not visible with a NEW one on the same row, that is the problem. It is difficult to find the OLD value of the record, since there might be many records in history if not hundreds or thousands in simultaneous transactions on the same record.

Two issues with this:
1. Permissions, some users might no be allowed to see history at all
2. Search History, as Davide says, it is really hard to find what was modified, since just says Modified :)

Like this one:
![Screenshot from 2019-03-12 20-53-09](https://user-images.githubusercontent.com/9026100/54201563-f3920a00-4508-11e9-926a-7bff8f34a980.png)


Not a biggie tho...

D.

**Comment by jam-py** [comment]
You are right, Dean
But the current content of the story and how it is visualized for the user
is
the result of a rather long evolution when used in various projects.

вт, 12 мар. 2019 г. в 15:54, platipusica <notifications@github.com>:
